import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Chheang Kuyky',
      email: 'kuyky1@gmail.com',
      password: bcrypt.hashSync('12345'),
      isAdmin: true,
    },
    {
      name: 'Pich Chansopheak',
      email: 'sopheak2@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],

  slideshows: [
    {
      image: '/images/1.png',
      title: 'Shoes Collection 2019',
      subtitle:
        'A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country',
    },
    {
      image: '/images/bg_1.png',
      title: 'Shoes Collection 2019',
      subtitle:
        'A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country',
    },
    {
      image: '/images/2.png',
      title: 'Shoes Collection 2019',
      subtitle:
        'A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country',
    },
  ],

  blogs: [
    { 
      image: '/images/image_1.jpg', 
      date: 'April 9, 2019' ,
      blogCreator: 'Admin',
      numComments: 3,
      title: 'Even the all-powerful Pointing has no control about the blind texts',
      description: 'Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.',
    }, 
    { 
      image: '/images/image_2.jpg', 
      date: 'April 9, 2019' ,
      blogCreator: 'Admin',
      numComments: 5,
      title: 'Even the all-powerful Pointing has no control about the blind texts',
      description: 'Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.',
    }, 
    { 
      image: '/images/image_3.jpg', 
      date: 'April 9, 2019' ,
      blogCreator: 'Admin',
      numComments: 2,
      title: 'Even the all-powerful Pointing has no control about the blind texts',
      description: 'Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.',
    }, 
    { 
      image: '/images/image_5.jpg', 
      date: 'April 9, 2019' ,
      blogCreator: 'Admin',
      numComments: 4,
      title: 'Even the all-powerful Pointing has no control about the blind texts',
      description: 'Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.',
    }, 
  ],

  products: [
    {
      // _id: '1',
      name: 'NIKE FREE RN 2019 ID1',
      slug: 'nike-free-rn-2019-id1',
      category: 'Men',
      image: '/images/product-1.png',
      price: 80,
      countInstock: 1,
      brand: 'Nike',
      rating: 4,
      numReviews: 10,
      description: 'high quality shoes',
    },
    {
      // _id: '2',
      name: 'NIKE FREE RN 2019 ID2',
      slug: 'nike-free-rn-2019-id2',
      category: 'Shoes',
      image: '/images/product-2.png',
      price: 70.0,
      countInstock: 5,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shoes',
    },
    {
      // _id: '3',
      name: 'NIKE FREE RN 2019 ID3',
      slug: 'nike-free-rn-2019-id3',
      category: 'Shoes',
      image: '/images/product-3.png',
      price: 130.0,
      countInstock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shoes',
    },
    {
      // _id: '4',
      name: 'NIKE FREE RN 2019 ID4',
      slug: 'nike-free-rn-2019-id4',
      category: 'Shoes',
      image: '/images/product-4.png',
      price: 95,
      countInstock: 5,
      brand: 'Nike',
      rating: 3.5,
      numReviews: 10,
      description: 'high quality shoes',
    },
    {
      // _id: '5',
      name: 'NIKE FREE RN 2019 ID5',
      slug: 'nike-free-rn-2019-id5',
      category: 'Shoes',
      image: '/images/product-5.png',
      price: 150.0,
      countInstock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shoes',
    },
    {
      // _id: '6',
      name: 'NIKE FREE RN 2019 ID6',
      slug: 'nike-free-rn-2019-id6',
      category: 'Shoes',
      image: '/images/product-6.png',
      price: 50,
      countInstock: 10,
      brand: 'Nike',
      rating: 5,
      numReviews: 10,
      description: 'high quality shoes',
    },
    {
      // _id: '7',
      name: 'NIKE FREE RN 2019 ID7',
      slug: 'nike-free-rn-2019-id7',
      category: 'Shoes',
      image: '/images/product-7.png',
      price: 70,
      countInstock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shoes',
    },
    {
      // _id: '8',
      name: 'NIKE FREE RN 2019 ID8',
      slug: 'nike-free-rn-2019-id8',
      category: 'Shirts',
      image: '/images/product-8.png',
      price: 100,
      countInstock: 10,
      brand: 'Nike',
      rating: 4,
      numReviews: 10,
      description: 'high quality shoes',
    },
    {
      name: 'NIKE FREE RN 2019 ID9',
      slug: 'nike-free-rn-2019-id9',
      category: 'Pants',
      image: '/images/product-5.png',
      price: 100,
      countInstock: 10,
      brand: 'Nike',
      rating: 4,
      numReviews: 10,
      description: 'high quality shoes',
    },
  ],
};

export default data;
